/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import com.macro.mall.CommentGenerator;
import java.util.Properties;
import org.junit.runner.RunWith;
import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.java.CompilationUnit;
import org.mybatis.generator.api.dom.java.Field;
import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class CommentGenerator_SSTest extends CommentGenerator_SSTest_scaffolding {
// allCoveredLines:[17, 18, 28, 29, 30, 38, 40, 43, 44, 47, 49, 56, 58, 59, 60, 62, 63, 64, 68, 70, 71, 73]

  @Test(timeout = 4000)
  public void test_addConfigurationProperties_0()  throws Throwable  {
      //caseID:944620560869f254b8f905c8610bc4fb
      //CoveredLines: [17, 18, 28, 29, 30]
      //Input_0_Properties: {}
      
      CommentGenerator commentGenerator0 = new CommentGenerator();
      //mock properties0
      Properties properties0 = mock(Properties.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      PrivateAccess.setVariable((Class<?>) CommentGenerator.class, commentGenerator0, "properties", (Object) properties0);
      //mock properties1
      Properties properties1 = mock(Properties.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: addConfigurationProperties
      commentGenerator0.addConfigurationProperties(properties1);
  }

  @Test(timeout = 4000)
  public void test_addFieldComment_1()  throws Throwable  {
      //caseID:ea6a557a1be661e9c7dcd7313a1363cd
      //CoveredLines: [17, 18, 38, 40, 49]
      //Input_0_Field: {}
      //Input_1_IntrospectedTable: {}
      //Input_2_IntrospectedColumn: {}
      
      CommentGenerator commentGenerator0 = new CommentGenerator();
      
      PrivateAccess.setVariable((Class<?>) CommentGenerator.class, commentGenerator0, "addRemarkComments", (Object) true);
      //mock field0
      Field field0 = mock(Field.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock introspectedTable0
      IntrospectedTable introspectedTable0 = mock(IntrospectedTable.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock introspectedColumn0
      IntrospectedColumn introspectedColumn0 = mock(IntrospectedColumn.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: addFieldComment
      commentGenerator0.addFieldComment(field0, introspectedTable0, introspectedColumn0);
  }

  @Test(timeout = 4000)
  public void test_addFieldComment_2()  throws Throwable  {
      //caseID:695551758598bb4661276efc6e31b4a4
      //CoveredLines: [17, 18, 38, 40, 49]
      //Input_0_Field: {}
      //Input_1_IntrospectedTable: {}
      //Input_2_IntrospectedColumn: {}
      
      CommentGenerator commentGenerator0 = new CommentGenerator();
      //mock field0
      Field field0 = mock(Field.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock introspectedTable0
      IntrospectedTable introspectedTable0 = mock(IntrospectedTable.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock introspectedColumn0
      IntrospectedColumn introspectedColumn0 = mock(IntrospectedColumn.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: addFieldComment
      commentGenerator0.addFieldComment(field0, introspectedTable0, introspectedColumn0);
  }

  @Test(timeout = 4000)
  public void test_addFieldComment_3()  throws Throwable  {
      //caseID:bd7ae5f931fba4eaa1d045f87496a955
      //CoveredLines: [17, 18, 38, 40, 43, 47, 49]
      //Input_0_Field: {}
      //Input_1_IntrospectedTable: {}
      //Input_2_IntrospectedColumn: {getRemarks=\"reactor.core.scheduler.DelegateServiceScheduler$UnsupportedScheduledExecutorService\"}
      
      CommentGenerator commentGenerator0 = new CommentGenerator();
      
      PrivateAccess.setVariable((Class<?>) CommentGenerator.class, commentGenerator0, "addRemarkComments", (Object) true);
      //mock field0
      Field field0 = mock(Field.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock introspectedTable0
      IntrospectedTable introspectedTable0 = mock(IntrospectedTable.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock introspectedColumn0
      IntrospectedColumn introspectedColumn0 = mock(IntrospectedColumn.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("reactor.core.scheduler.DelegateServiceScheduler$UnsupportedScheduledExecutorService").when(introspectedColumn0).getRemarks();
      
      //Call method: addFieldComment
      commentGenerator0.addFieldComment(field0, introspectedTable0, introspectedColumn0);
  }

  @Test(timeout = 4000)
  public void test_addFieldComment_4()  throws Throwable  {
      //caseID:efadac9fe8240e4598ab39a2845ca530
      //CoveredLines: [17, 18, 38, 40, 43, 44, 47, 49]
      //Input_0_Field: {}
      //Input_1_IntrospectedTable: {}
      //Input_2_IntrospectedColumn: {getRemarks=\"koJmk\\\"92F\"}
      
      CommentGenerator commentGenerator0 = new CommentGenerator();
      
      PrivateAccess.setVariable((Class<?>) CommentGenerator.class, commentGenerator0, "addRemarkComments", (Object) true);
      //mock field0
      Field field0 = mock(Field.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock introspectedTable0
      IntrospectedTable introspectedTable0 = mock(IntrospectedTable.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock introspectedColumn0
      IntrospectedColumn introspectedColumn0 = mock(IntrospectedColumn.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("koJmk\"92F").when(introspectedColumn0).getRemarks();
      
      //Call method: addFieldComment
      commentGenerator0.addFieldComment(field0, introspectedTable0, introspectedColumn0);
  }

  @Test(timeout = 4000)
  public void test_addFieldJavaDoc_5()  throws Throwable  {
      //caseID:32e0f9e74bea40a95ef4b59f43580795
      //CoveredLines: [17, 18, 56, 58, 59, 60, 62, 63, 64]
      //Input_0_org.mybatis.generator.api.dom.java.Field: {}
      //Input_1_String: 1.0
      
      CommentGenerator commentGenerator0 = new CommentGenerator();
      //mock field0
      Field field0 = mock(Field.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: addFieldJavaDoc
      PrivateAccess.callMethod((Class<CommentGenerator>) CommentGenerator.class, commentGenerator0, "addFieldJavaDoc", (Object) field0, (Class<?>) Field.class, (Object) "1.0", (Class<?>) String.class);
  }

  @Test(timeout = 4000)
  public void test_addJavaFileComment_6()  throws Throwable  {
      //caseID:ca05efaf6c111f76fe25c3144200699b
      //CoveredLines: [17, 18, 68, 70, 73]
      //Input_0_CompilationUnit: {getType=fullyQualifiedJavaType0}
      
      CommentGenerator commentGenerator0 = new CommentGenerator();
      //mock fullyQualifiedJavaType0
      FullyQualifiedJavaType fullyQualifiedJavaType0 = mock(FullyQualifiedJavaType.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("Example").when(fullyQualifiedJavaType0).getFullyQualifiedName();
      //mock compilationUnit0
      CompilationUnit compilationUnit0 = mock(CompilationUnit.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(fullyQualifiedJavaType0).when(compilationUnit0).getType();
      
      //Call method: addJavaFileComment
      commentGenerator0.addJavaFileComment(compilationUnit0);
  }

  @Test(timeout = 4000)
  public void test_addJavaFileComment_7()  throws Throwable  {
      //caseID:19770fe7e5abffb905940533c77d80ba
      //CoveredLines: [17, 18, 68, 70, 73]
      //Input_0_CompilationUnit: {getType=fullyQualifiedJavaType0}
      
      CommentGenerator commentGenerator0 = new CommentGenerator();
      //mock fullyQualifiedJavaType0
      FullyQualifiedJavaType fullyQualifiedJavaType0 = mock(FullyQualifiedJavaType.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("Mapper").when(fullyQualifiedJavaType0).getFullyQualifiedName();
      //mock compilationUnit0
      CompilationUnit compilationUnit0 = mock(CompilationUnit.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(fullyQualifiedJavaType0).when(compilationUnit0).getType();
      
      //Call method: addJavaFileComment
      commentGenerator0.addJavaFileComment(compilationUnit0);
  }

  @Test(timeout = 4000)
  public void test_addJavaFileComment_8()  throws Throwable  {
      //caseID:b1d61ac01586ccf14498f8fcc3daf2e0
      //CoveredLines: [17, 18, 68, 70, 71, 73]
      //Input_0_CompilationUnit: {getType=fullyQualifiedJavaType0}
      
      CommentGenerator commentGenerator0 = new CommentGenerator();
      //mock fullyQualifiedJavaType0
      FullyQualifiedJavaType fullyQualifiedJavaType0 = mock(FullyQualifiedJavaType.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("Error calling ApplicationEventListener").when(fullyQualifiedJavaType0).getFullyQualifiedName();
      //mock compilationUnit0
      CompilationUnit compilationUnit0 = mock(CompilationUnit.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(fullyQualifiedJavaType0).when(compilationUnit0).getType();
      
      //Call method: addJavaFileComment
      commentGenerator0.addJavaFileComment(compilationUnit0);
  }
}
