/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.security.component;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import static org.smartunit.runtime.SmartAssertions.*;
import com.macro.mall.security.component.DynamicSecurityMetadataSource;
import com.macro.mall.security.component.DynamicSecurityService;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import org.junit.runner.RunWith;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.ViolatedAssumptionAnswer;
import org.springframework.security.access.ConfigAttribute;
import org.springframework.security.access.SecurityConfig;
import org.springframework.security.web.FilterInvocation;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class DynamicSecurityMetadataSource_SSTest extends DynamicSecurityMetadataSource_SSTest_scaffolding {
// allCoveredLines:[18, 26, 27, 30, 36, 37, 39, 40, 41, 42, 44, 45, 46, 47, 49, 51, 56, 61]

  @Test(timeout = 4000)
  public void test_clearDataSource_0()  throws Throwable  {
      //caseID:f1763644d9d46ff5f21b24fc2c45d77c
      //CoveredLines: [18, 30]
      
      DynamicSecurityMetadataSource dynamicSecurityMetadataSource0 = new DynamicSecurityMetadataSource();
      
      //Call method: clearDataSource
      // Undeclared exception!
      try { 
        dynamicSecurityMetadataSource0.clearDataSource();
      } catch(Throwable e) {
         verifyException("com.macro.mall.security.component.DynamicSecurityMetadataSource", e);
         assertEquals("java.lang.NullPointerException", e.getClass().getName());
      }
  }

  @Test(timeout = 4000)
  public void test_getAllConfigAttributes_1()  throws Throwable  {
      //caseID:5e03f5eea99946a469269fb6e001bf73
      //CoveredLines: [18, 56]
      //Assert: assertNull(method_result);
      
      DynamicSecurityMetadataSource dynamicSecurityMetadataSource0 = new DynamicSecurityMetadataSource();
      
      //Call method: getAllConfigAttributes
      Collection<ConfigAttribute> collection0 = dynamicSecurityMetadataSource0.getAllConfigAttributes();
      
      //Test Result Assert
      assertNull(collection0);
  }

  @Test(timeout = 4000)
  public void test_getAttributes_2()  throws Throwable  {
      //caseID:d4e4203ef7d7b93a2ce21ff11ba18737
      //CoveredLines: [18, 26, 27, 36, 37, 39, 40, 41, 42, 44, 45, 46, 49, 51]
      //Input_0_Object: \"1\", \"\", \"1\", \"\", \"1\"
      //Assert: assertNotNull(method_result);
      
      DynamicSecurityMetadataSource dynamicSecurityMetadataSource0 = new DynamicSecurityMetadataSource();
      HashSet<String> hashSet0 = new HashSet<String>();
      
      hashSet0.add("] does not have a getId() method");
      //mock map0
      Map<String, ConfigAttribute> map0 = (Map<String, ConfigAttribute>) mock(Map.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(hashSet0).when(map0).keySet();
      //mock dynamicSecurityService0
      DynamicSecurityService dynamicSecurityService0 = mock(DynamicSecurityService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(map0).when(dynamicSecurityService0).loadDataSource();
      
      PrivateAccess.setVariable((Class<?>) DynamicSecurityMetadataSource.class, dynamicSecurityMetadataSource0, "dynamicSecurityService", (Object) dynamicSecurityService0);
      FilterInvocation filterInvocation0 = new FilterInvocation("1", "", "1", "", "1");
      
      //Call method: getAttributes
      Collection<ConfigAttribute> collection0 = dynamicSecurityMetadataSource0.getAttributes(filterInvocation0);
      
      //Test Result Assert
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test_getAttributes_3()  throws Throwable  {
      //caseID:7dfd676f79fd553059acd4198918a35e
      //CoveredLines: [18, 26, 27, 36, 37, 39, 40, 41, 42, 44, 45, 46, 47, 49, 51]
      //Input_0_Object: {getRequestUrl=\"\"}
      //Assert: assertTrue(method_result.contains(configAttribute0));
      
      DynamicSecurityMetadataSource dynamicSecurityMetadataSource0 = new DynamicSecurityMetadataSource();
      HashMap<String, ConfigAttribute> hashMap0 = new HashMap<String, ConfigAttribute>();
      //mock dynamicSecurityService0
      DynamicSecurityService dynamicSecurityService0 = mock(DynamicSecurityService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(hashMap0).when(dynamicSecurityService0).loadDataSource();
      
      PrivateAccess.setVariable((Class<?>) DynamicSecurityMetadataSource.class, dynamicSecurityMetadataSource0, "dynamicSecurityService", (Object) dynamicSecurityService0);
      //mock configAttribute0
      ConfigAttribute configAttribute0 = mock(ConfigAttribute.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("", "").when(configAttribute0).toString();
      
      hashMap0.put("", configAttribute0);
      //mock filterInvocation0
      FilterInvocation filterInvocation0 = mock(FilterInvocation.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("").when(filterInvocation0).getRequestUrl();
      
      //Call method: getAttributes
      Collection<ConfigAttribute> collection0 = dynamicSecurityMetadataSource0.getAttributes(filterInvocation0);
      
      //Test Result Assert
      assertTrue(collection0.contains(configAttribute0));
  }

  @Test(timeout = 4000)
  public void test_supports_4()  throws Throwable  {
      //caseID:8766903c521b11e1ed31d3b3253bf25d
      //CoveredLines: [18, 61]
      //Input_0_Class<?>: SecurityConfig.class
      //Assert: assertTrue(method_result);
      
      DynamicSecurityMetadataSource dynamicSecurityMetadataSource0 = new DynamicSecurityMetadataSource();
      Class<SecurityConfig> class0 = SecurityConfig.class;
      
      //Call method: supports
      boolean boolean0 = dynamicSecurityMetadataSource0.supports(class0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }
}
